blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("posts.urls")),
    path('users/', include("users.urls")),
    path('tinymce/', include("tinymce.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, re_path
from posts import views
from posts.views import UserPostListView, post_list, post_create, post_detail, post_update, post_delete, search, post, \
    CategoryView

app_name = 'posts'
urlpatterns = [
    path('', post_list, name='post-list'),
    path('post/<id>', post, name='post-detail'),
    re_path(r'^user/(?P<username>\w{0,50})/$', UserPostListView.as_view(), name='user-posts'),
    path('search/', search, name='search'),
    path('create/', post_create, name='post-create'),
    path('post/<id>/', post_detail, name='post-detail'),
    path('post/<id>/update/', post_update, name='post-update'),
    path('post/<id>/delete/', post_delete, name='post-delete'),

    path("author/<int:author_id>/", views.PostListAuthor.as_view(), name="author"),
    path('categories/<str:cats>/', CategoryView, name='categories'),

    path('about/', views.about, name="blog-about"),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from users import views as user_views
app_name='users'
urlpatterns = [
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/success/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

posts/models.py
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from tinymce import HTMLField


class PostView(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    post = models.ForeignKey('Post', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Author(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    profile_picture = models.ImageField()

    def __str__(self):
        return self.user.username


class Category(models.Model):
    title = models.CharField(max_length=20)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('post-list')

    class Meta:
        verbose_name_plural = "categories"


class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    timestamp = models.DateTimeField(auto_now_add=True)
    content = models.TextField()
    post = models.ForeignKey(
        'Post', related_name='comments', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username


class Post(models.Model):
    title = models.CharField(max_length=100)
    timestamp = models.DateTimeField(auto_now_add=True)
    content = HTMLField()
    author = models.ForeignKey(Author, on_delete=models.CASCADE)
    thumbnail = models.ImageField()
    categories = models.ManyToManyField(Category)
    featured = models.BooleanField(default=True)

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:post-detail', kwargs={
            'id': self.id
        })

    def get_update_url(self):
        return reverse('posts:post-update', kwargs={
            'id': self.id
        })

    def get_delete_url(self):
        return reverse('posts:post-delete', kwargs={
            'id': self.id
        })

    @property
    def get_comments(self):
        return self.comments.all().order_by('-timestamp')

    @property
    def comment_count(self):
        return Comment.objects.filter(post=self).count()

    @property
    def view_count(self):
        return PostView.objects.filter(post=self).count()

posts/forms.py
from django import forms
from tinymce import TinyMCE
from .models import Post, Comment


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False


class PostForm(forms.ModelForm):
    content = forms.CharField(
        widget=TinyMCEWidget(
            attrs={'required': False, 'cols': 30, 'rows': 10}
        )
    )

    class Meta:
        model = Post
        fields = ('title', 'content', 'thumbnail',
                  'categories', 'featured')


class CommentForm(forms.ModelForm):
    content = forms.CharField(widget=forms.Textarea(attrs={
        'class': 'form-control',
        'placeholder': 'Type your comment',
        'id': 'usercomment',
        'rows': '4'
    }))

    class Meta:
        model = Comment
        fields = ('content',)

posts/views.py
from django.db.models import Count, Q
from django.contrib.auth.models import User
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.shortcuts import render, get_object_or_404, redirect, reverse
from django.views.generic import ListView

from .forms import CommentForm, PostForm
from .models import Post, Author, PostView, Category


def get_author(user):
    qs = Author.objects.filter(user=user)
    if qs.exists():
        return qs[0]
    return None


def search(request):
    queryset = Post.objects.all()
    query = request.GET.get('q')
    if query:
        queryset = queryset.filter(
            Q(title__icontains=query) |
            Q(categories__title__icontains=query)
        ).order_by('-timestamp').distinct()
    context = {
        'queryset': queryset
    }
    return render(request, 'posts/search_results.html', context)


def get_category_count():
    queryset = Post \
        .objects \
        .values('categories__title') \
        .annotate(Count('categories__title'))
    return queryset


def post_list(request):
    category_count = get_category_count()
    most_recent = Post.objects.order_by('-timestamp')[:3]
    post_list = Post.objects.all()
    paginator = Paginator(post_list, 4)
    page_request_var = 'page'
    page = request.GET.get(page_request_var)
    cats = Category.objects.all()
    try:
        paginated_queryset = paginator.page(page)
    except PageNotAnInteger:
        paginated_queryset = paginator.page(1)
    except EmptyPage:
        paginated_queryset = paginator.page(paginator.num_pages)

    context = {
        'queryset': paginated_queryset,
        'most_recent': most_recent,
        'page_request_var': page_request_var,
        'category_count': category_count,

    }
    return render(request, 'posts/blog.html', context)


def CategoryView(request, cats):
    category_posts = Post.objects.filter(categories__title=cats.replace('-', ' '))
    return render(request, 'posts/categories.html',
                  {'cats': cats.replace('-', ' ').title(), 'category_posts': category_posts})


def post(request, id):
    post = get_object_or_404(Post, id=id)

    context = {
        'post': post
    }
    return render(request, 'posts:post.html', context)


class UserPostListView(ListView):
    model = Post
    template_name = 'posts/user_posts.html'
    context_object_name = 'posts'
    paginate_by = 4

    def get_queryset(self):
        user = get_object_or_404(User, username=self.kwargs.get('username'))
        return Post.objects.filter(author=user).order_by('-timestamp')


class PostListAuthor(ListView):
    model = Post, Author
    template_name = 'posts/post_author_list.html'
    context_object_name = 'author_posts'
    paginate_by = 4

    def get_queryset(self):
        author_id = self.kwargs['author_id']
        return Post.objects.filter(author=int(author_id)).order_by("-timestamp")


def post_detail(request, id):
    category_count = get_category_count()
    most_recent = Post.objects.order_by('-timestamp')[:3]
    post = get_object_or_404(Post, id=id)

    if request.user.is_authenticated:
        PostView.objects.get_or_create(user=request.user, post=post)

    form = CommentForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            form.instance.user = request.user
            form.instance.post = post
            form.save()
            return redirect(reverse("posts:post-detail", kwargs={
                'id': post.id
            }))
    context = {
        'post': post,
        'most_recent': most_recent,
        'category_count': category_count,
        'form': form
    }
    return render(request, 'posts/post.html', context)


def post_create(request):
    title = 'Create'
    form = PostForm(request.POST or None, request.FILES or None)
    author = get_author(request.user)
    if request.method == "POST":
        if form.is_valid():
            form.instance.author = author
            form.save()
            return redirect(reverse("posts:post-detail", kwargs={
                'id': form.instance.id
            }))
    context = {
        'title': title,
        'form': form
    }
    return render(request, "posts/post_create.html", context)


def post_update(request, id):
    title = 'Update'
    post = get_object_or_404(Post, id=id)
    form = PostForm(
        request.POST or None,
        request.FILES or None,
        instance=post)
    author = get_author(request.user)
    if request.method == "POST":
        if form.is_valid():
            form.instance.author = author
            form.save()
            return redirect(reverse("posts:post-detail", kwargs={
                'id': form.instance.id
            }))
    context = {
        'title': title,
        'form': form
    }
    return render(request, "posts/post_create.html", context)


def post_delete(request, id):
    post = get_object_or_404(Post, id=id)
    post.delete()
    return redirect(reverse("posts:post-list"))


def about(request):
    return render(request, 'posts/about.html')


def categoriesPage(request):
    q = request.GET.get('q') if request.GET.get('q') != None else ''
    categories = Category.objects.filter(title__icontains=q)
    return render(request, 'posts/categories.html', {'categories': categories})

templates/posts/about.html
{% extends "base.html" %}
{% block content %}
    <h1>About Page</h1>
{% endblock content %}

templates/posts/blog.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<!--user.id:{{user.id}} &nbsp; user.username:{{user.username}}-->

    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="posts-listing col-lg-8"> 
          <div class="container">
            <div class="row">
              <!-- post -->
               {% for post in queryset %}
              <div class="post col-xl-6">
                  <div class="post-thumbnail"><a href="{{ post.get_absolute_url }}"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></a></div>
                  <div class="post-details">
                    <div class="post-meta d-flex justify-content-between">
                      {% comment %} <div class="date meta-last">20 May | 2016</div> {% endcomment %}
                      <div class="category">
                      {% for cat in post.categories.all %}
                      <a href="{% url 'posts:categories' cat|slugify  %}">{{ cat }}</a>
                      {% endfor %}
                      </div>
                    </div>
                    <a href="{{ post.get_absolute_url }}">
                      <h3 class="h4">{{ post.title }}</h3>
                    </a>
                      <p class="text-muted">{{ post.content|safe|truncatechars:150 }}</p>
                      <footer class="post-footer d-flex align-items-center">
                        <a href="{% url 'posts:author' post.author.id %}" class="author d-flex align-items-center flex-wrap">
                          <div class="avatar"><img src="{{ post.author.profile_picture.url }}" alt="..." class="img-fluid"></div>
                          <div class="title"><span>{{ post.author.user.username }}</span></div>
                        </a>
                        <div class="date"><i class="icon-clock"></i>{{ post.timestamp|timesince }} ago</div>
                        <div class="comments meta-last"><i class="icon-comment"></i>{{ post.comment_count }}</div>
                      </footer>
                      </div>
                    </div>
              {% endfor %}
            </div>
            <!-- Pagination -->
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">
                {% if queryset.has_previous %}                
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.previous_page_number }}" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
                {% endif %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.number }}" class="page-link active">{{ queryset.number }}</a></li>
                {% if queryset.has_next %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.next_page_number }}" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
                {% endif %}
              </ul>
            </nav>

            {% if is_paginated %}
            
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">
                {% if page_obj.has_previous %}                
                <li class="page-item"><a href="?{{ page_request_var }}={{ page_obj.previous_page_number }}" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
                {% endif %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ page_obj.number }}" class="page-link active">{{ page_obj.number }}</a></li>
                {% if page_obj.has_next %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ page_obj.next_page_number }}" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
                {% endif %}
              </ul>
            </nav>
            {% endif %}
          </div>
        </main>
        {% include 'sidebar.html' with most_recent=most_recent category_count=category_count %}
      </div>
    </div>
{% endblock %}

templates/posts/categories.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h1>Posts of " {{ cats }} "  category </h1>

    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="posts-listing col-lg-8"> 
          <div class="container">
<!--           {% if category_posts %}-->
            <div class="row">
              <!-- post -->
               {% for post in category_posts %}
              <div class="post col-xl-6">
                  <div class="post-thumbnail"><a href="{{ post.get_absolute_url }}"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></a></div>
                  <div class="post-details">
                    <div class="post-meta d-flex justify-content-between">
                      {% comment %} <div class="date meta-last">20 May | 2016</div> {% endcomment %}
                      <div class="category">
                      {% for cat in post.categories.all %}
                      <a href="{% url 'posts:categories' cat|slugify  %}">{{ cat }}</a>
                      {% endfor %}
                      </div>
                    </div>
                    <a href="{{ post.get_absolute_url }}">
                      <h3 class="h4">{{ post.title }}</h3>
                    </a>
                      <p class="text-muted">{{ post.content|safe|truncatechars:150 }}</p>
                      <footer class="post-footer d-flex align-items-center">
                        <a href="#" class="author d-flex align-items-center flex-wrap">
                          <div class="avatar"><img src="{{ post.author.profile_picture.url }}" alt="..." class="img-fluid"></div>
                          <div class="title"><span>{{ post.author.user.username }}</span></div>
                        </a>
                        <div class="date"><i class="icon-clock"></i>{{ post.timestamp|timesince }} ago</div>
                        <div class="comments meta-last"><i class="icon-comment"></i>{{ post.comment_count }}</div>
                      </footer>
                      </div>
                    </div>
              {% endfor %}
            </div>
<!--                {% endif %}-->
            <!-- Pagination -->
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">
                {% if queryset.has_previous %}                
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.previous_page_number }}" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
                {% endif %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.number }}" class="page-link active">{{ queryset.number }}</a></li>
                {% if queryset.has_next %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.next_page_number }}" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
                {% endif %}
              </ul>
            </nav>

            {% if is_paginated %}
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">
                {% if page_obj.has_previous %}                
                <li class="page-item"><a href="?{{ page_request_var }}={{ page_obj.previous_page_number }}" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
                {% endif %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ page_obj.number }}" class="page-link active">{{ page_obj.number }}</a></li>
                {% if page_obj.has_next %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ page_obj.next_page_number }}" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
                {% endif %}
              </ul>
            </nav>
            {% endif %}
          </div>
        </main>
        {% include 'sidebar.html' with most_recent=most_recent category_count=category_count %}
      </div>
    </div>

{% endblock content %}

templates/posts/post.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<style>
  .post-body img {
    width: 100%;
  }
</style>

    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="post blog-post col-lg-8"> 
          <div class="container">
            <div class="post-single">
              <div class="post-thumbnail"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></div>
              <div class="post-details">
                <div class="post-meta d-flex justify-content-between">
                  <div class="category">
                    {% for cat in post.categories.all %}
                    <a href="#">{{ cat }}</a>
                    {% endfor %}
                  </div>
                  {% if user.is_authenticated and user.id == post.author.id %}
                  <div>
                    <a href="{% url 'posts:post-update' id=post.id %}">Update</a>
                    <a href="{% url 'posts:post-delete' id=post.id %}">Delete</a>
                  </div>
                  {% endif %}
                </div>
                <h1>{{ post.title }}<a href="#"><i class="fa fa-bookmark-o"></i></a></h1>
                <div class="post-footer d-flex align-items-center flex-column flex-sm-row"><a href="#" class="author d-flex align-items-center flex-wrap">
                    <div class="avatar"><img src="{{ post.author.profile_picture.url }}" alt="..." class="img-fluid"></div>
                    <div class="title">
                    <a class="mr-2" href="#">{{ post.author }}
                    </a>
                  </div>
                    <div class="d-flex align-items-center flex-wrap">
                    <div class="date"><i class="icon-clock"></i> {{ post.timestamp|timesince }} ago</div>
                    <div class="views"><i class="icon-eye"></i> {{ post.view_count }}</div>
                    <div class="comments meta-last"><i class="icon-comment"></i>{{ post.comment_count }}</div>
                  </div>
                </div>
                <div class="post-body">
                  {{ post.content | safe }}
                </div>
                <div class="posts-nav d-flex justify-content-between align-items-stretch flex-column flex-md-row">
                {% if post.previous_post %}
                <a href="{{ post.previous_post.get_absolute_url }}" class="prev-post text-left d-flex align-items-center">
                    <div class="icon prev"><i class="fa fa-angle-left"></i></div>
                    <div class="text"><strong class="text-primary">Previous Post </strong>
                      <h6>{{ post.previous_post.title }}</h6>
                    </div>
                </a>
                {% endif %}
                {% if post.next_post %}
                <a href="{{ post.next_post.get_absolute_url }}" class="next-post text-right d-flex align-items-center justify-content-end">
                    <div class="text"><strong class="text-primary">Next Post </strong>
                      <h6>{{ post.next_post.title }}</h6>
                    </div>
                    <div class="icon next"><i class="fa fa-angle-right">   </i></div>
                </a>
                {% endif %}
                </div>
                <div class="post-comments">
                  <header>
                    <h3 class="h6">Post Comments<span class="no-of-comments">({{ post.comments.count }})</span></h3>
                  </header>
                  {% for comment in post.get_comments %}
                  <div class="comment">
                    <div class="comment-header d-flex justify-content-between">
                      <div class="user d-flex align-items-center">
                        <div class="image">
                          {% if comment.user.author %}
                          <img src="{{ comment.user.author.profile_picture.url }}" alt="..." class="img-fluid rounded-circle">
                          {% elif comment.user.username %}
                          <img src="{{ comment.user.profile.image.url }}" alt="..." class="img-fluid rounded-circle">
                          {% else %}
                          <img src="{% static 'img/user.svg' %}" alt="..." class="img-fluid rounded-circle">
                          {% endif %}
                        </div>
                        <div class="title"><strong>{{ comment.user.username }}</strong><span class="date">{{ comment.timestamp|timesince }} ago</span></div>
                      </div>
                    </div>
                    <div class="comment-body">
                      <p>{{ comment.content }}</p>
                    </div>
                  </div>
                  {% endfor %}
                </div>
                {% if request.user.is_authenticated %}
                <div class="add-comment">
                  <header>
                    <h3 class="h6">Leave a reply</h3>
                  </header>
                  <form method="POST" action="." class="commenting-form">
                    {% csrf_token %}
                    <div class="row">
                      <div class="form-group col-md-12">
                        {{ form }}
                      </div>
                      <div class="form-group col-md-12">
                        <button type="submit" class="btn btn-secondary">Submit Comment</button>
                      </div>
                    </div>
                  </form>
                </div>
                {% else %}
                <a href="{% url 'users:login' %}" class="btn btn-primary">Login to comment</a>
                {% endif %}
              </div>
            </div>
          </div>
        </main>
        {% include 'sidebar.html' with most_recent=most_recent category_count=category_count %}        
      </div>
    </div>
{% endblock content %}

templates/posts/post_author_list.html
{% extends 'base.html' %}
{% load static %}

{% block content %}


<h1 class="mb-12">Posts by:  No of {{ view.kwargs.username }}'s posts is  ({{ page_obj.paginator.count }})</h1>
{{view.kwargs.author_id}}
    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="posts-listing col-lg-8">
          <div class="container">
            <div class="row">
              <!-- post -->
              {% if author_posts %}
               {% for post in author_posts  %}
              <div class="post col-xl-6">
                  <div class="post-thumbnail"><a href="{{ post.get_absolute_url }}"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></a></div>
                  <div class="post-details">
                    <div class="post-meta d-flex justify-content-between">
                      {% comment %} <div class="date meta-last">20 May | 2016</div> {% endcomment %}
                      <div class="category">
                      {% for cat in post.categories.all %}
                      <a href="{% url 'posts:categories' cat|slugify  %}">{{ cat }}</a>
                      {% endfor %}
                      </div>
                    </div>
                    <a href="{{ post.get_absolute_url }}">
                      <h3 class="h4">{{ post.title }}</h3>
                    </a>
                      <p class="text-muted">{{ post.content|safe|truncatechars:150 }}</p>
                      <footer class="post-footer d-flex align-items-center">
                        <a href="{% url 'posts:author' post.author.id  %}" class="author d-flex align-items-center flex-wrap">
                          <div class="avatar"><img src="{{ post.author.profile_picture.url }}" alt="..." class="img-fluid"></div>
                          <div class="title"><span>{{ post.author.user.username }}</span></div>
                        </a>
                        <div class="date"><i class="icon-clock"></i>{{ post.timestamp|timesince }} ago</div>
                        <div class="comments meta-last"><i class="icon-comment"></i>{{ post.comment_count }}</div>
                      </footer>
                      </div>
                    </div>
              {% endfor %}
              {% endif %}
            </div>
            <!-- Pagination -->
            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">
                {% if queryset.has_previous %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.previous_page_number }}" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
                {% endif %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.number }}" class="page-link active">{{ queryset.number }}</a></li>
                {% if queryset.has_next %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ queryset.next_page_number }}" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
                {% endif %}
              </ul>
            </nav>

            {% if is_paginated %}

            <nav aria-label="Page navigation example">
              <ul class="pagination pagination-template d-flex justify-content-center">
                {% if page_obj.has_previous %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ page_obj.previous_page_number }}" class="page-link"> <i class="fa fa-angle-left"></i></a></li>
                {% endif %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ page_obj.number }}" class="page-link active">{{ page_obj.number }}</a></li>
                {% if page_obj.has_next %}
                <li class="page-item"><a href="?{{ page_request_var }}={{ page_obj.next_page_number }}" class="page-link"> <i class="fa fa-angle-right"></i></a></li>
                {% endif %}
              </ul>
            </nav>
            {% endif %}
          </div>
        </main>
        {% include 'sidebar.html' with most_recent=most_recent category_count=category_count %}
      </div>
    </div>

{% endblock %}

templates/posts/post_confirm_delete.html
{% extends 'base.html' %}

{% block content %}

    <div class="container">
      <div class="row">
        <!-- Latest Posts -->
        <main class="post blog-post col-lg-8"> 
          <div class="container">
            <p>Are you sure you want to delete "{{ object }}"?</p>
            <form method="post">
                {% csrf_token %}
                <input type="submit" value="Confirm">
            </form>
          </div>
        </main>
        {% include 'sidebar.html' with most_recent=most_recent category_count=category_count %}        
      </div>
    </div>
{% endblock content %}

templates/posts/post_create.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}

    {% if user.author %}
<div class="col-4 offset-4 mb-5 mt-5">
<h3>{{ title }} an article</h3>
{{ form.media }}
<form method="POST" action="." enctype="multipart/form-data">
    {% csrf_token %}

    {{ form|crispy }}

    <button class="btn btn-primary" type="submit">Submit</button>
</form>
    {% else %}
    Execuse me {{request.user.username}},You aren't authorised as an author,
    {% endif %}
</div>

{% endblock content %}

templates/posts/search_results.html
{% extends 'base.html' %}
{% load static %}

{% block content %}

<h2>This is the results of your search</h2>
{% for post in queryset %}
    <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
    <br />
{% endfor %}

{% endblock %}