blog/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include("posts.urls")),
    path('users/', include("users.urls")),
    path('tinymce/', include("tinymce.urls")),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

posts/urls.py
from django.urls import path, re_path
from posts import views
from posts.views import UserPostListView, post_list, post_create, post_detail, post_update, post_delete, search, post, \
    CategoryView

app_name = 'posts'
urlpatterns = [
    path('', post_list, name='post-list'),
    path('post/<id>', post, name='post-detail'),
    re_path(r'^user/(?P<username>\w{0,50})/$', UserPostListView.as_view(), name='user-posts'),
    path('search/', search, name='search'),
    path('create/', post_create, name='post-create'),
    path('post/<id>/', post_detail, name='post-detail'),
    path('post/<id>/update/', post_update, name='post-update'),
    path('post/<id>/delete/', post_delete, name='post-delete'),

    path("author/<int:author_id>/", views.PostListAuthor.as_view(), name="author"),
    path('categories/<str:cats>/', CategoryView, name='categories'),

    path('about/', views.about, name="blog-about"),
]

users/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from users import views as user_views
app_name='users'
urlpatterns = [
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='users/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='users/logout.html'), name='logout'),
    path('profile/', user_views.profile, name='profile'),
    path('password-reset/', auth_views.PasswordResetView.as_view(template_name='users/password_reset.html'), name='password_reset'),
    path('password-reset/success/', auth_views.PasswordResetDoneView.as_view(template_name='users/password_reset_done.html'), name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/', auth_views.PasswordResetConfirmView.as_view(template_name='users/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password-reset-complete/', auth_views.PasswordResetCompleteView.as_view(template_name='users/password_reset_complete.html'), name='password_reset_complete'),
]

templates/base.html
<!DOCTYPE html>
<html>

{% include "head.html" %}

<body>

    {% include 'header.html' %}

    {% if messages %}
        <ul class="messages">
            {% for message in messages %}
            <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
            {% endfor %}
        </ul>
    {% endif %}

    {% block content %}
    {% endblock content %}

    {% include 'footer.html' %}
    {% include 'scripts.html' %}

</body>

</html>

templates/footer.html
{% load static %}
<footer class="main-footer">
      <div class="container">
        <div class="row">
          <div class="col-md-4">
            <div class="logo">
              <h6 class="text-white">Bootstrap Blog</h6>
            </div>
            <div class="contact-details">
              <p>53 Broadway, Broklyn, NY 11249</p>
              <p>Phone: (020) 123 456 789</p>
              <p>Email: <a href="mailto:info@company.com">Info@Company.com</a></p>
              <ul class="social-menu">
                <li class="list-inline-item"><a href="#"><i class="fa fa-facebook"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-twitter"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-instagram"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-behance"></i></a></li>
                <li class="list-inline-item"><a href="#"><i class="fa fa-pinterest"></i></a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
            <div class="menus d-flex">
              <ul class="list-unstyled">
                <li> <a href="#">My Account</a></li>
                <li> <a href="#">Add Listing</a></li>
                <li> <a href="#">Pricing</a></li>
                <li> <a href="#">Privacy &amp; Policy</a></li>
              </ul>
              <ul class="list-unstyled">
                <li> <a href="#">Our Partners</a></li>
                <li> <a href="#">FAQ</a></li>
                <li> <a href="#">How It Works</a></li>
                <li> <a href="#">Contact</a></li>
              </ul>
            </div>
          </div>
          <div class="col-md-4">
            <div class="latest-posts"><a href="#">
                <div class="post d-flex align-items-center">
                  <div class="image"><img src="{% static 'img/small-thumbnail-1.jpg' %}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>Hotels for all budgets</strong><span class="date last-meta">October 26, 2016</span></div>
                </div></a><a href="#">
                <div class="post d-flex align-items-center">
                  <div class="image"><img src="{% static 'img/small-thumbnail-2.jpg' %}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>Great street atrs in London</strong><span class="date last-meta">October 26, 2016</span></div>
                </div></a><a href="#">
                <div class="post d-flex align-items-center">
                  <div class="image"><img src="{% static 'img/small-thumbnail-3.jpg' %}" alt="..." class="img-fluid"></div>
                  <div class="title"><strong>Best coffee shops in Sydney</strong><span class="date last-meta">October 26, 2016</span></div>
                </div></a></div>
          </div>
        </div>
      </div>
      <div class="copyrights">
        <div class="container">
          <div class="row">
            <div class="col-md-6">
              <p>&copy; 2017. All rights reserved. Your great site.</p>
            </div>
            <div class="col-md-6 text-right">
              <p>Template By <a href="https://bootstraptemple.com" class="text-white">Bootstrap Temple</a>
                <!-- Please do not remove the backlink to Bootstrap Temple unless you purchase an attribution-free license @ Bootstrap Temple or support us at http://bootstrapious.com/donate. It is part of the license conditions. Thanks for understanding :)                         -->
              </p>
            </div>
          </div>
        </div>
      </div>
    </footer>

templates/head.html
{% load static %}
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Bootstrap Blog - B4 Template by Bootstrap Temple</title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="robots" content="all,follow">
    <link rel="stylesheet" href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'vendor/font-awesome/css/font-awesome.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/fontastic.css' %}">
    <link rel="stylesheet" href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,700">
    <link rel="stylesheet" href="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.default.css' %}" id="theme-stylesheet">
    <link rel="stylesheet" href="{% static 'css/custom.css' %}">
    <link rel="shortcut icon" href="{% static 'favicon.png' %}">

    <link href='{% static "styles/github.css" %}' rel="stylesheet">

    <!-- Tweaks for older IEs--><!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
        <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script><![endif]-->
  </head>

templates/header.html
    <header class="header">
      <!-- Main Navbar-->
      <nav class="navbar navbar-expand-lg">
        <div class="search-area">
          <div class="search-area-inner d-flex align-items-center justify-content-center">
            <div class="close-btn"><i class="icon-close"></i></div>
            <div class="row d-flex justify-content-center">
              <div class="col-md-8">
                <form action="{% url 'posts:search' %}">
                  <div class="form-group">
                    <input type="search" name="q" id="search" placeholder="What are you looking for?">
                    <button type="submit" class="submit"><i class="icon-search-1"></i></button>
                  </div>
                </form>
              </div>
            </div>
          </div>
        </div>
        <div class="container">
          <!-- Navbar Brand -->
          <div class="navbar-header d-flex align-items-center justify-content-between">
            <!-- Navbar Brand --><a href="/" class="navbar-brand">Bootstrap Blog</a>
            <!-- Toggle Button-->
            <button type="button" data-toggle="collapse" data-target="#navbarcollapse" aria-controls="navbarcollapse" aria-expanded="false" aria-label="Toggle navigation" class="navbar-toggler"><span></span><span></span><span></span></button>
          </div>
          <!-- Navbar Menu -->

          <div id="navbarcollapse" class="collapse navbar-collapse">
            <ul class="navbar-nav ml-auto">
              <li class="nav-item"><a href="/" class="nav-link ">Home</a>
              </li>
               <li class="nav-item"><a href="url 'posts:posts/about.html'" class="nav-link ">About</a>
              </li>
              <li class="nav-item"><a href="#" class="nav-link ">Contact</a>
              </li>

               {% if user.is_authenticated %}
                <li class="nav-item"><a href="{% url 'posts:post-create' %}" class="nav-link ">Create Post</a>
                </li>
                <li class="nav-item"><a href="{% url 'users:profile' %}" class="nav-link ">Profile</a>
                </li>
                <li class="nav-item"><a href="{% url 'users:logout' %}" class="nav-link ">Logout</a>
                </li>
              {% else %}
                <li class="nav-item"><a href="{% url 'users:login' %}" class="nav-link ">Login</a>
                </li>
                <li class="nav-item"><a href="{% url 'users:register' %}" class="nav-link ">Register</a>
                </li>
              {% endif %}
            </ul>
            <div class="navbar-text"><a href="#" class="search-btn"><i class="icon-search-1"></i></a></div>
            {% comment %} <ul class="langs navbar-text"><a href="#" class="active">EN</a><span>           </span><a href="#">ES</a></ul> {% endcomment %}
          </div>
        </div>
      </nav>
    </header>

templates/scripts.html
{% load static %}
<!-- JavaScript files-->
<script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
<script src="{% static 'vendor/popper.js/umd/popper.min.js' %}"> </script>
<script src="{% static 'vendor/bootstrap/js/bootstrap.min.js' %}"></script>
<script src="{% static 'vendor/jquery.cookie/jquery.cookie.js' %}"> </script>
<script src="{% static 'vendor/@fancyapps/fancybox/jquery.fancybox.min.js' %}"></script>
<script src="{% static 'js/front.js' %}"></script>

<script src='{% static "js/highlight.pack.js" %}'></script>
<script>hljs.initHighlightingOnLoad();</script>

templates/sidebar.html
<aside class="col-lg-4">
    <!-- Widget [Search Bar Widget]-->
    <div class="widget search">
    <header>
        <h3 class="h6">Search the blog</h3>
    </header>
    <form action="{% url 'posts:search' %}" class="search-form">
        <div class="form-group">
        <input type="text" name="q" placeholder="What are you looking for?">
        <button type="submit" class="submit"><i class="icon-search"></i></button>
        </div>
    </form>
    </div>
    <!-- Widget [Latest Posts Widget]        -->
    <div class="widget latest-posts">
    <header>
        <h3 class="h6">Latest Posts</h3>
    </header>
    <div class="blog-posts">
        {% for post in most_recent %}
            <a href="{{ post.get_absolute_url }}">
            <div class="item d-flex align-items-center">
            <div class="image"><img src="{{ post.thumbnail.url }}" alt="..." class="img-fluid"></div>
            <div class="title"><strong>{{ post.title }}</strong>
                <div class="d-flex align-items-center">
                <div class="views"><i class="icon-eye"></i> {{ post.view_count }}</div>
                <div class="comments"><i class="icon-comment"></i>{{ post.comment_count }}</div>
                </div>
            </div>
            </div>
        </a>
        {% endfor %}
    </div>
    <!-- Widget [Categories Widget]-->
    <div class="widget categories">
    <header>
        <h3 class="h6">Categories</h3>
    </header>
    <div class="item d-flex justify-content-between">
        <a href="{% url 'posts:post-list' %}">All</a><span>{{ category_count.count }}</span>
    </div>
    {% for cat in category_count %}
    <div class="item d-flex justify-content-between" name="q" >
        <a href="{% url 'posts:categories' cat.categories__title %}">{{ cat.categories__title }}</a><span>{{ cat.categories__title__count }}</span>
    </div>
    {% endfor %}
    </div>
</aside>